EXPO_project/EXPO_app/urls.py
from django.conf.urls import url, include
from . import Read_view, Create_view, Update_view, Delete_view, List_view, Home_view, preferences, registration

urlpatterns = [
    url(r'^home/$', Home_view.HomeView, name='HomeView'),

    url(r'^preferences/$', preferences.define_preferences, name='define_preferences'),

    url(r'^signup/$', registration.signup, name='signup'),    

    url(r'^Thing/create/$', Create_view.ThingCreate, name='ThingCreate'),

    url(r'^RepresentationForm/create/$', Create_view.RepresentationFormCreate, name='RepresentationFormCreate'),

    url(r'^Artifact/create/$', Create_view.ArtifactCreate, name='ArtifactCreate'),

    url(r'^SynonymousExternalConcept/create/$', Create_view.SynonymousExternalConceptCreate, name='SynonymousExternalConceptCreate'),

    url(r'^Name/create/$', Create_view.NameCreate, name='NameCreate'),

    url(r'^ScientificExperiment/create/$', Create_view.ScientificExperimentCreate, name='ScientificExperimentCreate'),

    url(r'^ExperimentalDesign/create/$', Create_view.ExperimentalDesignCreate, name='ExperimentalDesignCreate'),

    url(r'^AdminInfoExperiment/create/$', Create_view.AdminInfoExperimentCreate, name='AdminInfoExperimentCreate'),

    url(r'^IDExperiment/create/$', Create_view.IDExperimentCreate, name='IDExperimentCreate'),

    url(r'^DomainOfExperiment/create/$', Create_view.DomainOfExperimentCreate, name='DomainOfExperimentCreate'),

    url(r'^ExperimentalObservation/create/$', Create_view.ExperimentalObservationCreate, name='ExperimentalObservationCreate'),

    url(r'^ResultsInterpretation/create/$', Create_view.ResultsInterpretationCreate, name='ResultsInterpretationCreate'),

    url(r'^ExperimentalAction/create/$', Create_view.ExperimentalActionCreate, name='ExperimentalActionCreate'),

    url(r'^ActionName/create/$', Create_view.ActionNameCreate, name='ActionNameCreate'),

    url(r'^ActionComplexity/create/$', Create_view.ActionComplexityCreate, name='ActionComplexityCreate'),

    url(r'^Human/create/$', Create_view.HumanCreate, name='HumanCreate'),

    url(r'^Organization/create/$', Create_view.OrganizationCreate, name='OrganizationCreate'),

    url(r'^AdminInfoAuthor/create/$', Create_view.AdminInfoAuthorCreate, name='AdminInfoAuthorCreate'),

    url(r'^AdminInfoObjectOfExperiment/create/$', Create_view.AdminInfoObjectOfExperimentCreate, name='AdminInfoObjectOfExperimentCreate'),

    url(r'^AdminInfoProvider/create/$', Create_view.AdminInfoProviderCreate, name='AdminInfoProviderCreate'),

    url(r'^AdminInfoSubjectOfExperiment/create/$', Create_view.AdminInfoSubjectOfExperimentCreate, name='AdminInfoSubjectOfExperimentCreate'),

    url(r'^AdminInfoSubmitter/create/$', Create_view.AdminInfoSubmitterCreate, name='AdminInfoSubmitterCreate'),

    url(r'^AdminInfoUser/create/$', Create_view.AdminInfoUserCreate, name='AdminInfoUserCreate'),

    url(r'^ExperimentalMethod/create/$', Create_view.ExperimentalMethodCreate, name='ExperimentalMethodCreate'),

    url(r'^MethodApplicabilityCondition/create/$', Create_view.MethodApplicabilityConditionCreate, name='MethodApplicabilityConditionCreate'),

    url(r'^StandardOperatingProcedure/create/$', Create_view.StandardOperatingProcedureCreate, name='StandardOperatingProcedureCreate'),

    url(r'^Author/create/$', Create_view.AuthorCreate, name='AuthorCreate'),

    url(r'^ClassificationOfDomains/create/$', Create_view.ClassificationOfDomainsCreate, name='ClassificationOfDomainsCreate'),

    url(r'^ClassificationOfExperiments/create/$', Create_view.ClassificationOfExperimentsCreate, name='ClassificationOfExperimentsCreate'),

    url(r'^ExperimentalHypothesis/create/$', Create_view.ExperimentalHypothesisCreate, name='ExperimentalHypothesisCreate'),

    url(r'^HypothesisComplexity/create/$', Create_view.HypothesisComplexityCreate, name='HypothesisComplexityCreate'),

    url(r'^Representation/create/$', Create_view.RepresentationCreate, name='RepresentationCreate'),

    url(r'^Proposition/create/$', Create_view.PropositionCreate, name='PropositionCreate'),

    url(r'^ExperimentalEquipment/create/$', Create_view.ExperimentalEquipmentCreate, name='ExperimentalEquipmentCreate'),

    url(r'^TechnicalDescription/create/$', Create_view.TechnicalDescriptionCreate, name='TechnicalDescriptionCreate'),

    url(r'^ExperimentalResults/create/$', Create_view.ExperimentalResultsCreate, name='ExperimentalResultsCreate'),

    url(r'^ObservationalError/create/$', Create_view.ObservationalErrorCreate, name='ObservationalErrorCreate'),

    url(r'^ResultError/create/$', Create_view.ResultErrorCreate, name='ResultErrorCreate'),

    url(r'^ResultsEvaluation/create/$', Create_view.ResultsEvaluationCreate, name='ResultsEvaluationCreate'),

    url(r'^ScientificInvestigation/create/$', Create_view.ScientificInvestigationCreate, name='ScientificInvestigationCreate'),

    url(r'^ExperimentalModel/create/$', Create_view.ExperimentalModelCreate, name='ExperimentalModelCreate'),

    url(r'^ExperimentalFactor/create/$', Create_view.ExperimentalFactorCreate, name='ExperimentalFactorCreate'),

    url(r'^ExperimentalTechnology/create/$', Create_view.ExperimentalTechnologyCreate, name='ExperimentalTechnologyCreate'),

    url(r'^ExperimentalRequirements/create/$', Create_view.ExperimentalRequirementsCreate, name='ExperimentalRequirementsCreate'),

    url(r'^HypothesisExplicitness/create/$', Create_view.HypothesisExplicitnessCreate, name='HypothesisExplicitnessCreate'),

    url(r'^LinguisticExpression/create/$', Create_view.LinguisticExpressionCreate, name='LinguisticExpressionCreate'),

    url(r'^FactRejectResearchHypothesis/create/$', Create_view.FactRejectResearchHypothesisCreate, name='FactRejectResearchHypothesisCreate'),

    url(r'^FactSupportResearchHypothesis/create/$', Create_view.FactSupportResearchHypothesisCreate, name='FactSupportResearchHypothesisCreate'),

    url(r'^Number/create/$', Create_view.NumberCreate, name='NumberCreate'),

    url(r'^GeneralityOfHypothesis/create/$', Create_view.GeneralityOfHypothesisCreate, name='GeneralityOfHypothesisCreate'),

    url(r'^ActionGoal/create/$', Create_view.ActionGoalCreate, name='ActionGoalCreate'),

    url(r'^ExperimentalGoal/create/$', Create_view.ExperimentalGoalCreate, name='ExperimentalGoalCreate'),

    url(r'^MethodGoal/create/$', Create_view.MethodGoalCreate, name='MethodGoalCreate'),

    url(r'^HypothesisFormation/create/$', Create_view.HypothesisFormationCreate, name='HypothesisFormationCreate'),

    url(r'^HypothesisRepresentation/create/$', Create_view.HypothesisRepresentationCreate, name='HypothesisRepresentationCreate'),

    url(r'^InformationGethering/create/$', Create_view.InformationGetheringCreate, name='InformationGetheringCreate'),

    url(r'^Sample/create/$', Create_view.SampleCreate, name='SampleCreate'),

    url(r'^Variability/create/$', Create_view.VariabilityCreate, name='VariabilityCreate'),

    url(r'^TimePoint/create/$', Create_view.TimePointCreate, name='TimePointCreate'),

    url(r'^User/create/$', Create_view.UserCreate, name='UserCreate'),

    url(r'^LoginName/create/$', Create_view.LoginNameCreate, name='LoginNameCreate'),

    url(r'^DomainModel/create/$', Create_view.DomainModelCreate, name='DomainModelCreate'),

    url(r'^GroupExperimentalObject/create/$', Create_view.GroupExperimentalObjectCreate, name='GroupExperimentalObjectCreate'),

    url(r'^ObjectOfExperiment/create/$', Create_view.ObjectOfExperimentCreate, name='ObjectOfExperimentCreate'),

    url(r'^ClassificationByModel/create/$', Create_view.ClassificationByModelCreate, name='ClassificationByModelCreate'),

    url(r'^StatisticsCharacteristic/create/$', Create_view.StatisticsCharacteristicCreate, name='StatisticsCharacteristicCreate'),

    url(r'^ParentGroup/create/$', Create_view.ParentGroupCreate, name='ParentGroupCreate'),

    url(r'^Password/create/$', Create_view.PasswordCreate, name='PasswordCreate'),

    url(r'^ProcedureExecuteExperiment/create/$', Create_view.ProcedureExecuteExperimentCreate, name='ProcedureExecuteExperimentCreate'),

    url(r'^PlanOfExperimentalActions/create/$', Create_view.PlanOfExperimentalActionsCreate, name='PlanOfExperimentalActionsCreate'),

    url(r'^PoblemAnalysis/create/$', Create_view.PoblemAnalysisCreate, name='PoblemAnalysisCreate'),

    url(r'^SubjectQualification/create/$', Create_view.SubjectQualificationCreate, name='SubjectQualificationCreate'),

    url(r'^BiblioReference/create/$', Create_view.BiblioReferenceCreate, name='BiblioReferenceCreate'),

    url(r'^Model/create/$', Create_view.ModelCreate, name='ModelCreate'),

    url(r'^ModelRepresentation/create/$', Create_view.ModelRepresentationCreate, name='ModelRepresentationCreate'),

    url(r'^RepresentationExperimentalExecutionProcedure/create/$', Create_view.RepresentationExperimentalExecutionProcedureCreate, name='RepresentationExperimentalExecutionProcedureCreate'),

    url(r'^RepresentationExperimentalGoal/create/$', Create_view.RepresentationExperimentalGoalCreate, name='RepresentationExperimentalGoalCreate'),

    url(r'^SampleRepresentativeness/create/$', Create_view.SampleRepresentativenessCreate, name='SampleRepresentativenessCreate'),

    url(r'^SampleSize/create/$', Create_view.SampleSizeCreate, name='SampleSizeCreate'),

    url(r'^SamplingMethod/create/$', Create_view.SamplingMethodCreate, name='SamplingMethodCreate'),

    url(r'^SystematicSampling/create/$', Create_view.SystematicSamplingCreate, name='SystematicSamplingCreate'),

    url(r'^SamplingRule/create/$', Create_view.SamplingRuleCreate, name='SamplingRuleCreate'),

    url(r'^ExperimentalStandard/create/$', Create_view.ExperimentalStandardCreate, name='ExperimentalStandardCreate'),

    url(r'^Error/create/$', Create_view.ErrorCreate, name='ErrorCreate'),

    url(r'^Dispersion/create/$', Create_view.DispersionCreate, name='DispersionCreate'),

    url(r'^LevelOfSignificance/create/$', Create_view.LevelOfSignificanceCreate, name='LevelOfSignificanceCreate'),

EXPO_project/EXPO_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'EXPO_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^vowl', 'EXPO_app.Home_view.vowl', name='vowl'),
    url(r'^EXPO_app/', include('EXPO_app.urls', namespace='EXPO_app')),
    url(r'^$', 'EXPO_app.Home_view.HomeView', name='HomeView'),    url(r'^accounts/',include('django.contrib.auth.urls')),]

EXPO_project/EXPO_app/views.py
from django.shortcuts import render

# Create your views here.

EXPO_project/EXPO_app/templates/DomainActionUpdate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:DomainActionUpdate' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Update</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

EXPO_project/EXPO_app/templates/ExecutionOfExperimentCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:ExecutionOfExperimentCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

EXPO_project/EXPO_app/templates/ExperimentalModelDelete.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:ExperimentalModelDelete' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Delete</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

EXPO_project/EXPO_app/templates/FalsePpositiveDelete.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:FalsePpositiveDelete' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Delete</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

EXPO_project/EXPO_app/templates/GroupExperimentalObjectCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:GroupExperimentalObjectCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

EXPO_project/EXPO_app/templates/LanguageCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:LanguageCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

EXPO_project/EXPO_app/templates/VariabilityCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'EXPO_app:VariabilityCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}