MarineTLO_project/MarineTLO_app/urls.py
from django.conf.urls import url, include
from . import Read_view, Create_view, Update_view, Delete_view, List_view, Home_view, preferences, registration

urlpatterns = [
    url(r'^home/$', Home_view.HomeView, name='HomeView'),

    url(r'^preferences/$', preferences.define_preferences, name='define_preferences'),

    url(r'^signup/$', registration.signup, name='signup'),    

    url(r'^BC35_Physical_Thing/create/$', Create_view.BC35_Physical_ThingCreate, name='BC35_Physical_ThingCreate'),

    url(r'^BC10_Event/create/$', Create_view.BC10_EventCreate, name='BC10_EventCreate'),

    url(r'^BC8_Actor/create/$', Create_view.BC8_ActorCreate, name='BC8_ActorCreate'),

    url(r'^BC34_Geometric_Place_Expression/create/$', Create_view.BC34_Geometric_Place_ExpressionCreate, name='BC34_Geometric_Place_ExpressionCreate'),

    url(r'^BC29_Spatial_Coordinate_Reference_System/create/$', Create_view.BC29_Spatial_Coordinate_Reference_SystemCreate, name='BC29_Spatial_Coordinate_Reference_SystemCreate'),

    url(r'^BC56_Digital_Measurement_Event/create/$', Create_view.BC56_Digital_Measurement_EventCreate, name='BC56_Digital_Measurement_EventCreate'),

    url(r'^BC23_Digital_Object/create/$', Create_view.BC23_Digital_ObjectCreate, name='BC23_Digital_ObjectCreate'),

    url(r'^BC18_Proposition/create/$', Create_view.BC18_PropositionCreate, name='BC18_PropositionCreate'),

    url(r'^BC59_Software/create/$', Create_view.BC59_SoftwareCreate, name='BC59_SoftwareCreate'),

    url(r'^BC58_Digital_Device/create/$', Create_view.BC58_Digital_DeviceCreate, name='BC58_Digital_DeviceCreate'),

    url(r'^BC61_Capture_Activity/create/$', Create_view.BC61_Capture_ActivityCreate, name='BC61_Capture_ActivityCreate'),

    url(r'^BC57_Capture/create/$', Create_view.BC57_CaptureCreate, name='BC57_CaptureCreate'),

    url(r'^BC54_Measurement/create/$', Create_view.BC54_MeasurementCreate, name='BC54_MeasurementCreate'),

    url(r'^BC44_Attribute_Assignment/create/$', Create_view.BC44_Attribute_AssignmentCreate, name='BC44_Attribute_AssignmentCreate'),

    url(r'^BC1_TLO_Entity/create/$', Create_view.BC1_TLO_EntityCreate, name='BC1_TLO_EntityCreate'),

    url(r'^BC43_Activity/create/$', Create_view.BC43_ActivityCreate, name='BC43_ActivityCreate'),

    url(r'^BC4_Temporal_Phenomenon/create/$', Create_view.BC4_Temporal_PhenomenonCreate, name='BC4_Temporal_PhenomenonCreate'),

    url(r'^BC3_Place/create/$', Create_view.BC3_PlaceCreate, name='BC3_PlaceCreate'),

    url(r'^BC45_Observation/create/$', Create_view.BC45_ObservationCreate, name='BC45_ObservationCreate'),

    url(r'^BC9_Observable_Entity/create/$', Create_view.BC9_Observable_EntityCreate, name='BC9_Observable_EntityCreate'),

    url(r'^BC7_Thing/create/$', Create_view.BC7_ThingCreate, name='BC7_ThingCreate'),

    url(r'^BC5_Dimension/create/$', Create_view.BC5_DimensionCreate, name='BC5_DimensionCreate'),

    url(r'^BC30_Appellation/create/$', Create_view.BC30_AppellationCreate, name='BC30_AppellationCreate'),

    url(r'^BC55_Measurement_Unit/create/$', Create_view.BC55_Measurement_UnitCreate, name='BC55_Measurement_UnitCreate'),

    url(r'^BC20_Declarative_Place/create/$', Create_view.BC20_Declarative_PlaceCreate, name='BC20_Declarative_PlaceCreate'),

    url(r'^BC72_SpaceTime_Volume/create/$', Create_view.BC72_SpaceTime_VolumeCreate, name='BC72_SpaceTime_VolumeCreate'),

    url(r'^BC2_Time_Span/create/$', Create_view.BC2_Time_SpanCreate, name='BC2_Time_SpanCreate'),

    url(r'^BT14_Appellation_Type/create/$', Create_view.BT14_Appellation_TypeCreate, name='BT14_Appellation_TypeCreate'),

    url(r'^BT2_Temporal_Phenomenon_Type/create/$', Create_view.BT2_Temporal_Phenomenon_TypeCreate, name='BT2_Temporal_Phenomenon_TypeCreate'),

    url(r'^BT10_Biotic_Element_Type/create/$', Create_view.BT10_Biotic_Element_TypeCreate, name='BT10_Biotic_Element_TypeCreate'),

    url(r'^BT7_Ecosystem_Type/create/$', Create_view.BT7_Ecosystem_TypeCreate, name='BT7_Ecosystem_TypeCreate'),

    url(r'^BT4_Conceptual_Object_Type/create/$', Create_view.BT4_Conceptual_Object_TypeCreate, name='BT4_Conceptual_Object_TypeCreate'),

    url(r'^BT1_TLO_Entity_Type/create/$', Create_view.BT1_TLO_Entity_TypeCreate, name='BT1_TLO_Entity_TypeCreate'),

    url(r'^BT17_Human_Activity_Type/create/$', Create_view.BT17_Human_Activity_TypeCreate, name='BT17_Human_Activity_TypeCreate'),

    url(r'^BT9_Actor_Type/create/$', Create_view.BT9_Actor_TypeCreate, name='BT9_Actor_TypeCreate'),

    url(r'^BT32_Persistent_Type/create/$', Create_view.BT32_Persistent_TypeCreate, name='BT32_Persistent_TypeCreate'),

    url(r'^BC32_Identifier/create/$', Create_view.BC32_IdentifierCreate, name='BC32_IdentifierCreate'),

    url(r'^BC64_Design_or_Procedure/create/$', Create_view.BC64_Design_or_ProcedureCreate, name='BC64_Design_or_ProcedureCreate'),

    url(r'^BC79_Right/create/$', Create_view.BC79_RightCreate, name='BC79_RightCreate'),

    url(r'^BC6_Persistent_Item/create/$', Create_view.BC6_Persistent_ItemCreate, name='BC6_Persistent_ItemCreate'),

    url(r'^BT3_Physical_Thing_Type/create/$', Create_view.BT3_Physical_Thing_TypeCreate, name='BT3_Physical_Thing_TypeCreate'),

    url(r'^BC17_Conceptual_Object/create/$', Create_view.BC17_Conceptual_ObjectCreate, name='BC17_Conceptual_ObjectCreate'),

    url(r'^BT32_Persisten_Type/create/$', Create_view.BT32_Persisten_TypeCreate, name='BT32_Persisten_TypeCreate'),

    url(r'^BC39_Marine_Animal/create/$', Create_view.BC39_Marine_AnimalCreate, name='BC39_Marine_AnimalCreate'),

    url(r'^BC40_Physical_ManMade_Thing/create/$', Create_view.BC40_Physical_ManMade_ThingCreate, name='BC40_Physical_ManMade_ThingCreate'),

    url(r'^BC41_ManMade_Object/create/$', Create_view.BC41_ManMade_ObjectCreate, name='BC41_ManMade_ObjectCreate'),

    url(r'^BC42_Collection/create/$', Create_view.BC42_CollectionCreate, name='BC42_CollectionCreate'),

    url(r'^BC46_Identifier_Assignment/create/$', Create_view.BC46_Identifier_AssignmentCreate, name='BC46_Identifier_AssignmentCreate'),

    url(r'^BC47_Image/create/$', Create_view.BC47_ImageCreate, name='BC47_ImageCreate'),

    url(r'^BC48_Database/create/$', Create_view.BC48_DatabaseCreate, name='BC48_DatabaseCreate'),

    url(r'^BC53_Specimen/create/$', Create_view.BC53_SpecimenCreate, name='BC53_SpecimenCreate'),

    url(r'^BC60_Software_Execution/create/$', Create_view.BC60_Software_ExecutionCreate, name='BC60_Software_ExecutionCreate'),

    url(r'^BC62_Statistic_Indicator/create/$', Create_view.BC62_Statistic_IndicatorCreate, name='BC62_Statistic_IndicatorCreate'),

    url(r'^BC63_Global_Statistic_Landing/create/$', Create_view.BC63_Global_Statistic_LandingCreate, name='BC63_Global_Statistic_LandingCreate'),

    url(r'^BC70_Group/create/$', Create_view.BC70_GroupCreate, name='BC70_GroupCreate'),

    url(r'^BC71_Name_Use_Activity/create/$', Create_view.BC71_Name_Use_ActivityCreate, name='BC71_Name_Use_ActivityCreate'),

    url(r'^BC75_Stock/create/$', Create_view.BC75_StockCreate, name='BC75_StockCreate'),

    url(r'^BC76_Stock_Formation/create/$', Create_view.BC76_Stock_FormationCreate, name='BC76_Stock_FormationCreate'),

    url(r'^BC77_Matter_Removal/create/$', Create_view.BC77_Matter_RemovalCreate, name='BC77_Matter_RemovalCreate'),

    url(r'^BC78_Amount_of_Matter/create/$', Create_view.BC78_Amount_of_MatterCreate, name='BC78_Amount_of_MatterCreate'),

    url(r'^BT11_Equipment_Type/create/$', Create_view.BT11_Equipment_TypeCreate, name='BT11_Equipment_TypeCreate'),

    url(r'^BT12_Scientific_Data_Type/create/$', Create_view.BT12_Scientific_Data_TypeCreate, name='BT12_Scientific_Data_TypeCreate'),

    url(r'^BT13_Digital_Object_Type/create/$', Create_view.BT13_Digital_Object_TypeCreate, name='BT13_Digital_Object_TypeCreate'),

    url(r'^BT16_Visual_Type/create/$', Create_view.BT16_Visual_TypeCreate, name='BT16_Visual_TypeCreate'),

    url(r'^BT6_Human_Event_Type/create/$', Create_view.BT6_Human_Event_TypeCreate, name='BT6_Human_Event_TypeCreate'),

    url(r'^BT18_Kingdom/create/$', Create_view.BT18_KingdomCreate, name='BT18_KingdomCreate'),

    url(r'^BT19_Phylum/create/$', Create_view.BT19_PhylumCreate, name='BT19_PhylumCreate'),

    url(r'^BT20_SubPhylum/create/$', Create_view.BT20_SubPhylumCreate, name='BT20_SubPhylumCreate'),

    url(r'^BT21_SuperClass/create/$', Create_view.BT21_SuperClassCreate, name='BT21_SuperClassCreate'),

    url(r'^BT35_Property_Type/create/$', Create_view.BT35_Property_TypeCreate, name='BT35_Property_TypeCreate'),

    url(r'^BC25_Linguistic_Object/create/$', Create_view.BC25_Linguistic_ObjectCreate, name='BC25_Linguistic_ObjectCreate'),

    url(r'^BT36_Language/create/$', Create_view.BT36_LanguageCreate, name='BT36_LanguageCreate'),

    url(r'^BC11_Person/create/$', Create_view.BC11_PersonCreate, name='BC11_PersonCreate'),

    url(r'^BC12_Ecosystem/create/$', Create_view.BC12_EcosystemCreate, name='BC12_EcosystemCreate'),

    url(r'^BC13_Organization/create/$', Create_view.BC13_OrganizationCreate, name='BC13_OrganizationCreate'),

    url(r'^BC14_Ecosystem_Environment/create/$', Create_view.BC14_Ecosystem_EnvironmentCreate, name='BC14_Ecosystem_EnvironmentCreate'),

    url(r'^BC15_Water_Area/create/$', Create_view.BC15_Water_AreaCreate, name='BC15_Water_AreaCreate'),

    url(r'^BC16_ManMade_thing/create/$', Create_view.BC16_ManMade_thingCreate, name='BC16_ManMade_thingCreate'),

    url(r'^BC19_Title/create/$', Create_view.BC19_TitleCreate, name='BC19_TitleCreate'),

    url(r'^BC21_DataSet/create/$', Create_view.BC21_DataSetCreate, name='BC21_DataSetCreate'),

    url(r'^BC22_Encounter_Event/create/$', Create_view.BC22_Encounter_EventCreate, name='BC22_Encounter_EventCreate'),

    url(r'^BC24_Repository_Object/create/$', Create_view.BC24_Repository_ObjectCreate, name='BC24_Repository_ObjectCreate'),

    url(r'^BC26_Place_Name/create/$', Create_view.BC26_Place_NameCreate, name='BC26_Place_NameCreate'),

MarineTLO_project/MarineTLO_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'MarineTLO_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^vowl', 'MarineTLO_app.Home_view.vowl', name='vowl'),
    url(r'^MarineTLO_app/', include('MarineTLO_app.urls', namespace='MarineTLO_app')),
    url(r'^$', 'MarineTLO_app.Home_view.HomeView', name='HomeView'),    url(r'^accounts/',include('django.contrib.auth.urls')),]

MarineTLO_project/MarineTLO_app/views.py
from django.shortcuts import render

# Create your views here.

MarineTLO_project/MarineTLO_app/templates/BC19_TitleDelete.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'MarineTLO_app:BC19_TitleDelete' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Delete</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BC1_TLO_EntityList.html
{% extends 'home.html'%}
{% block content %}
        <div class='ui center aligned segment container'>
        <h2>BC1_TLO_Entity</h2>
        <div class="ui one column stackable center aligned page grid">
            <div class="twelve wide column">
                <a  href="{% url 'MarineTLO_app:BC1_TLO_EntityCreate'%}">
                        <button type="button">Create</button> 
                </a>
            </div>
            <div class='column twelve wide'>
            {% if  data %}
            <table class="ui celled table">
                <thead>
                    <tr>
                        {% for field in fields%}
                        <th>{{field}}</th>
                         {% endfor %}
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                     {% for instance in data %}
                        <tr>
                             {% for field, value in instance.fields.items %}
                            <td>
                             {{ value }}
                            </td>
                             {% endfor %}
                              <td>
                                <a href="{% url 'MarineTLO_app:BC1_TLO_EntityRead' instance.pk%}">
                                        <button>View</button>
                                </a>
                                 <a href="{% url 'MarineTLO_app:BC1_TLO_EntityUpdate' instance.pk %}">
                                        <button>Update</button>
                                 </a>
                                 <a href="{% url 'MarineTLO_app:BC1_TLO_EntityDelete' instance.pk %}">
                                        <button>Delete</button>
                                 </a>
                             </td>
                        <tr>
                         {% endfor %}
                    </tr>
                    </tbody>
            </table>
            {%endif%}
            </div>
        </div>
    </div>
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BC21_DataSetDelete.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'MarineTLO_app:BC21_DataSetDelete' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Delete</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BC21_DataSetRead.html
{% extends 'home.html'%}
{% block content %}
<div class='ui center aligned segment container'>
    <div class="ui grid">
        <div class="ui column">
            <div class="ui segment">
                    {% for item in instance_items %}
                    <div class="item">
                        <div class="ui horizontal label">
                                    {{item.key}}
                                </div><span> {{item.value}}</span>
                    </div>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BC3_PlaceCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'MarineTLO_app:BC3_PlaceCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BC44_Attribute_AssignmentCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'MarineTLO_app:BC44_Attribute_AssignmentCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BC63_Global_Statistic_LandingCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'MarineTLO_app:BC63_Global_Statistic_LandingCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

MarineTLO_project/MarineTLO_app/templates/BT21_SuperClassCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'MarineTLO_app:BT21_SuperClassCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}