iedm_project/iedm_app/urls.py
from django.conf.urls import url, include
from . import Read_view, Create_view, Update_view, Delete_view, List_view, Home_view, preferences, registration

urlpatterns = [
    url(r'^home/$', Home_view.HomeView, name='HomeView'),

    url(r'^preferences/$', preferences.define_preferences, name='define_preferences'),

    url(r'^signup/$', registration.signup, name='signup'),    

    url(r'^Thing/create/$', Create_view.ThingCreate, name='ThingCreate'),

    url(r'^Object/create/$', Create_view.ObjectCreate, name='ObjectCreate'),

    url(r'^UnaryFunction/create/$', Create_view.UnaryFunctionCreate, name='UnaryFunctionCreate'),

    url(r'^User/create/$', Create_view.UserCreate, name='UserCreate'),

    url(r'^IrradiationFacilityRole/create/$', Create_view.IrradiationFacilityRoleCreate, name='IrradiationFacilityRoleCreate'),

    url(r'^IrradiationFacilityCoordinator/create/$', Create_view.IrradiationFacilityCoordinatorCreate, name='IrradiationFacilityCoordinatorCreate'),

    url(r'^IrradiationFacilityManager/create/$', Create_view.IrradiationFacilityManagerCreate, name='IrradiationFacilityManagerCreate'),

    url(r'^Operator/create/$', Create_view.OperatorCreate, name='OperatorCreate'),

    url(r'^ResponsiblePerson/create/$', Create_view.ResponsiblePersonCreate, name='ResponsiblePersonCreate'),

    url(r'^DUTIrradiation/create/$', Create_view.DUTIrradiationCreate, name='DUTIrradiationCreate'),

    url(r'^Sample/create/$', Create_view.SampleCreate, name='SampleCreate'),

    url(r'^DUT/create/$', Create_view.DUTCreate, name='DUTCreate'),

    url(r'^LayerTable/create/$', Create_view.LayerTableCreate, name='LayerTableCreate'),

    url(r'^IrradiationExperiment/create/$', Create_view.IrradiationExperimentCreate, name='IrradiationExperimentCreate'),

    url(r'^Layer/create/$', Create_view.LayerCreate, name='LayerCreate'),

    url(r'^Compound/create/$', Create_view.CompoundCreate, name='CompoundCreate'),

    url(r'^CompoundWeightFractionTable/create/$', Create_view.CompoundWeightFractionTableCreate, name='CompoundWeightFractionTableCreate'),

    url(r'^IrradiationFacility/create/$', Create_view.IrradiationFacilityCreate, name='IrradiationFacilityCreate'),

    url(r'^Physical/create/$', Create_view.PhysicalCreate, name='PhysicalCreate'),

    url(r'^IrradiationFacilityUser/create/$', Create_view.IrradiationFacilityUserCreate, name='IrradiationFacilityUserCreate'),

    url(r'^Predicate/create/$', Create_view.PredicateCreate, name='PredicateCreate'),

    url(r'^SentientAgent/create/$', Create_view.SentientAgentCreate, name='SentientAgentCreate'),

    url(r'^Agent/create/$', Create_view.AgentCreate, name='AgentCreate'),

    url(r'^CompoundWeightFractionEntry/create/$', Create_view.CompoundWeightFractionEntryCreate, name='CompoundWeightFractionEntryCreate'),

    url(r'^Element/create/$', Create_view.ElementCreate, name='ElementCreate'),

    url(r'^UnaryFunctionEntry/create/$', Create_view.UnaryFunctionEntryCreate, name='UnaryFunctionEntryCreate'),

    url(r'^CumulatedQuantity/create/$', Create_view.CumulatedQuantityCreate, name='CumulatedQuantityCreate'),

    url(r'^IrradiationExperimentObject/create/$', Create_view.IrradiationExperimentObjectCreate, name='IrradiationExperimentObjectCreate'),

    url(r'^InteractionLength/create/$', Create_view.InteractionLengthCreate, name='InteractionLengthCreate'),

    url(r'^InteractionLengthOccupancy/create/$', Create_view.InteractionLengthOccupancyCreate, name='InteractionLengthOccupancyCreate'),

    url(r'^DosimetricQuantity/create/$', Create_view.DosimetricQuantityCreate, name='DosimetricQuantityCreate'),

    url(r'^Dosimeter/create/$', Create_view.DosimeterCreate, name='DosimeterCreate'),

    url(r'^DomainOfExperiment/create/$', Create_view.DomainOfExperimentCreate, name='DomainOfExperimentCreate'),

    url(r'^ParticlePhysicsExperiment/create/$', Create_view.ParticlePhysicsExperimentCreate, name='ParticlePhysicsExperimentCreate'),

    url(r'^Requirements/create/$', Create_view.RequirementsCreate, name='RequirementsCreate'),

    url(r'^MonitoringSystem/create/$', Create_view.MonitoringSystemCreate, name='MonitoringSystemCreate'),

    url(r'^StorageArea/create/$', Create_view.StorageAreaCreate, name='StorageAreaCreate'),

    url(r'^FieldOfStudy/create/$', Create_view.FieldOfStudyCreate, name='FieldOfStudyCreate'),

    url(r'^IrradiationFacilityPostion/create/$', Create_view.IrradiationFacilityPostionCreate, name='IrradiationFacilityPostionCreate'),

    url(r'^Length/create/$', Create_view.LengthCreate, name='LengthCreate'),

    url(r'^Percentage/create/$', Create_view.PercentageCreate, name='PercentageCreate'),

    url(r'^LayerEntry/create/$', Create_view.LayerEntryCreate, name='LayerEntryCreate'),

    url(r'^Relation/create/$', Create_view.RelationCreate, name='RelationCreate'),

    url(r'^Abstract/create/$', Create_view.AbstractCreate, name='AbstractCreate'),

    url(r'^Region/create/$', Create_view.RegionCreate, name='RegionCreate'),

    url(r'^SubjectRole/create/$', Create_view.SubjectRoleCreate, name='SubjectRoleCreate'),

    url(r'^ActorRole/create/$', Create_view.ActorRoleCreate, name='ActorRoleCreate'),

    url(r'^AbsorbedDose/create/$', Create_view.AbsorbedDoseCreate, name='AbsorbedDoseCreate'),

    url(r'^AbsorbedDoseInMedium/create/$', Create_view.AbsorbedDoseInMediumCreate, name='AbsorbedDoseInMediumCreate'),

    url(r'^Quantity/create/$', Create_view.QuantityCreate, name='QuantityCreate'),

    url(r'^Activity/create/$', Create_view.ActivityCreate, name='ActivityCreate'),

    url(r'^DosimetricRate/create/$', Create_view.DosimetricRateCreate, name='DosimetricRateCreate'),

    url(r'^AtomicMass/create/$', Create_view.AtomicMassCreate, name='AtomicMassCreate'),

    url(r'^Mass/create/$', Create_view.MassCreate, name='MassCreate'),

    url(r'^Density/create/$', Create_view.DensityCreate, name='DensityCreate'),

    url(r'^Energy/create/$', Create_view.EnergyCreate, name='EnergyCreate'),

    url(r'^Height/create/$', Create_view.HeightCreate, name='HeightCreate'),

    url(r'^Number/create/$', Create_view.NumberCreate, name='NumberCreate'),

    url(r'^Ratio/create/$', Create_view.RatioCreate, name='RatioCreate'),

    url(r'^Temperature/create/$', Create_view.TemperatureCreate, name='TemperatureCreate'),

    url(r'^Thickness/create/$', Create_view.ThicknessCreate, name='ThicknessCreate'),

    url(r'^AbsorbedDoseInAir/create/$', Create_view.AbsorbedDoseInAirCreate, name='AbsorbedDoseInAirCreate'),

    url(r'^AdminInfoIrradiationExperiment/create/$', Create_view.AdminInfoIrradiationExperimentCreate, name='AdminInfoIrradiationExperimentCreate'),

    url(r'^AdminInfoExperiment/create/$', Create_view.AdminInfoExperimentCreate, name='AdminInfoExperimentCreate'),

    url(r'^ActionrelatedRole/create/$', Create_view.ActionrelatedRoleCreate, name='ActionrelatedRoleCreate'),

    url(r'^Role/create/$', Create_view.RoleCreate, name='RoleCreate'),

    url(r'^AdministrativeInformation/create/$', Create_view.AdministrativeInformationCreate, name='AdministrativeInformationCreate'),

    url(r'^Proposition/create/$', Create_view.PropositionCreate, name='PropositionCreate'),

    url(r'^AdminInfoObjectOfExperiment/create/$', Create_view.AdminInfoObjectOfExperimentCreate, name='AdminInfoObjectOfExperimentCreate'),

    url(r'^AdminInfoUser/create/$', Create_view.AdminInfoUserCreate, name='AdminInfoUserCreate'),

    url(r'^Classification/create/$', Create_view.ClassificationCreate, name='ClassificationCreate'),

    url(r'^ScientificTask/create/$', Create_view.ScientificTaskCreate, name='ScientificTaskCreate'),

    url(r'^ClassificationByDomain/create/$', Create_view.ClassificationByDomainCreate, name='ClassificationByDomainCreate'),

    url(r'^ClassificationOfExperiments/create/$', Create_view.ClassificationOfExperimentsCreate, name='ClassificationOfExperimentsCreate'),

    url(r'^CorpuscularObject/create/$', Create_view.CorpuscularObjectCreate, name='CorpuscularObjectCreate'),

    url(r'^SelfConnectedObject/create/$', Create_view.SelfConnectedObjectCreate, name='SelfConnectedObjectCreate'),

    url(r'^ExperimentalRequirements/create/$', Create_view.ExperimentalRequirementsCreate, name='ExperimentalRequirementsCreate'),

    url(r'^AdminInfoIrradiationExperimentUser/create/$', Create_view.AdminInfoIrradiationExperimentUserCreate, name='AdminInfoIrradiationExperimentUserCreate'),

    url(r'^AdminInfoObjectOfIrradiation/create/$', Create_view.AdminInfoObjectOfIrradiationCreate, name='AdminInfoObjectOfIrradiationCreate'),

    url(r'^AdminInfoObjectOfIrradiationExperiment/create/$', Create_view.AdminInfoObjectOfIrradiationExperimentCreate, name='AdminInfoObjectOfIrradiationExperimentCreate'),

    url(r'^AtomicNumber/create/$', Create_view.AtomicNumberCreate, name='AtomicNumberCreate'),

    url(r'^CollaborationRequirements/create/$', Create_view.CollaborationRequirementsCreate, name='CollaborationRequirementsCreate'),

    url(r'^ControlRoom/create/$', Create_view.ControlRoomCreate, name='ControlRoomCreate'),

    url(r'^ControlSystem/create/$', Create_view.ControlSystemCreate, name='ControlSystemCreate'),

    url(r'^System/create/$', Create_view.SystemCreate, name='SystemCreate'),

    url(r'^RadiationLength/create/$', Create_view.RadiationLengthCreate, name='RadiationLengthCreate'),

    url(r'^RadiationLengthOccupancy/create/$', Create_view.RadiationLengthOccupancyCreate, name='RadiationLengthOccupancyCreate'),

    url(r'^RadioprotectionRequirements/create/$', Create_view.RadioprotectionRequirementsCreate, name='RadioprotectionRequirementsCreate'),

    url(r'^SingularField/create/$', Create_view.SingularFieldCreate, name='SingularFieldCreate'),

    url(r'^RadiationField/create/$', Create_view.RadiationFieldCreate, name='RadiationFieldCreate'),

    url(r'^TechnicalRequirements/create/$', Create_view.TechnicalRequirementsCreate, name='TechnicalRequirementsCreate'),

iedm_project/iedm_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'iedm_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^vowl', 'iedm_app.Home_view.vowl', name='vowl'),
    url(r'^iedm_app/', include('iedm_app.urls', namespace='iedm_app')),
    url(r'^$', 'iedm_app.Home_view.HomeView', name='HomeView'),    url(r'^accounts/',include('django.contrib.auth.urls')),]

iedm_project/iedm_app/views.py
from django.shortcuts import render

# Create your views here.

iedm_project/iedm_app/templates/AbsorbedDoseInMediumDelete.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'iedm_app:AbsorbedDoseInMediumDelete' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Delete</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

iedm_project/iedm_app/templates/Action-relatedRoleList.html
{% extends 'home.html'%}
{% block content %}
        <div class='ui center aligned segment container'>
        <h2>Action-relatedRole</h2>
        <div class="ui one column stackable center aligned page grid">
            <div class="twelve wide column">
                <a  href="{% url 'iedm_app:Action-relatedRoleCreate'%}">
                        <button type="button">Create</button> 
                </a>
            </div>
            <div class='column twelve wide'>
            {% if  data %}
            <table class="ui celled table">
                <thead>
                    <tr>
                        {% for field in fields%}
                        <th>{{field}}</th>
                         {% endfor %}
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                     {% for instance in data %}
                        <tr>
                             {% for field, value in instance.fields.items %}
                            <td>
                             {{ value }}
                            </td>
                             {% endfor %}
                              <td>
                                <a href="{% url 'iedm_app:Action-relatedRoleRead' instance.pk%}">
                                        <button>View</button>
                                </a>
                                 <a href="{% url 'iedm_app:Action-relatedRoleUpdate' instance.pk %}">
                                        <button>Update</button>
                                 </a>
                                 <a href="{% url 'iedm_app:Action-relatedRoleDelete' instance.pk %}">
                                        <button>Delete</button>
                                 </a>
                             </td>
                        <tr>
                         {% endfor %}
                    </tr>
                    </tbody>
            </table>
            {%endif%}
            </div>
        </div>
    </div>
{% endblock %}

iedm_project/iedm_app/templates/ActorRoleUpdate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'iedm_app:ActorRoleUpdate' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Update</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

iedm_project/iedm_app/templates/AtomicMassUpdate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'iedm_app:AtomicMassUpdate' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Update</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

iedm_project/iedm_app/templates/AtomicNumberCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'iedm_app:AtomicNumberCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

iedm_project/iedm_app/templates/AtomicNumberRead.html
{% extends 'home.html'%}
{% block content %}
<div class='ui center aligned segment container'>
    <div class="ui grid">
        <div class="ui column">
            <div class="ui segment">
                    {% for item in instance_items %}
                    <div class="item">
                        <div class="ui horizontal label">
                                    {{item.key}}
                                </div><span> {{item.value}}</span>
                    </div>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

iedm_project/iedm_app/templates/ClassificationByDomainCreate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'iedm_app:ClassificationByDomainCreate'%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Create</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

iedm_project/iedm_app/templates/DomainOfExperimentDelete.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'iedm_app:DomainOfExperimentDelete' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Delete</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}