sosa_project/sosa_app/urls.py
from django.conf.urls import url, include
from . import Read_view, Create_view, Update_view, Delete_view, List_view, Home_view, preferences, registration

urlpatterns = [
    url(r'^home/$', Home_view.HomeView, name='HomeView'),

    url(r'^preferences/$', preferences.define_preferences, name='define_preferences'),

    url(r'^signup/$', registration.signup, name='signup'),    

    url(r'^Agent/create/$', Create_view.AgentCreate, name='AgentCreate'),

    url(r'^TemporalEntity/create/$', Create_view.TemporalEntityCreate, name='TemporalEntityCreate'),

    url(r'^Procedure/create/$', Create_view.ProcedureCreate, name='ProcedureCreate'),

    url(r'^Vocabulary/create/$', Create_view.VocabularyCreate, name='VocabularyCreate'),

    url(r'^Actuation/create/$', Create_view.ActuationCreate, name='ActuationCreate'),

    url(r'^ActuatableProperty/create/$', Create_view.ActuatablePropertyCreate, name='ActuatablePropertyCreate'),

    url(r'^Observation/create/$', Create_view.ObservationCreate, name='ObservationCreate'),

    url(r'^Sampling/create/$', Create_view.SamplingCreate, name='SamplingCreate'),

    url(r'^FeatureOfInterest/create/$', Create_view.FeatureOfInterestCreate, name='FeatureOfInterestCreate'),

    url(r'^Sample/create/$', Create_view.SampleCreate, name='SampleCreate'),

    url(r'^Result/create/$', Create_view.ResultCreate, name='ResultCreate'),

    url(r'^Platform/create/$', Create_view.PlatformCreate, name='PlatformCreate'),

    url(r'^Actuator/create/$', Create_view.ActuatorCreate, name='ActuatorCreate'),

    url(r'^Sampler/create/$', Create_view.SamplerCreate, name='SamplerCreate'),

    url(r'^Sensor/create/$', Create_view.SensorCreate, name='SensorCreate'),

    url(r'^ObservableProperty/create/$', Create_view.ObservablePropertyCreate, name='ObservablePropertyCreate'),


    url(r'^Agent/(?P<pk>\d+)/read/$', Read_view.AgentRead, name='AgentRead'),

    url(r'^TemporalEntity/(?P<pk>\d+)/read/$', Read_view.TemporalEntityRead, name='TemporalEntityRead'),

    url(r'^Procedure/(?P<pk>\d+)/read/$', Read_view.ProcedureRead, name='ProcedureRead'),

    url(r'^Vocabulary/(?P<pk>\d+)/read/$', Read_view.VocabularyRead, name='VocabularyRead'),

    url(r'^Actuation/(?P<pk>\d+)/read/$', Read_view.ActuationRead, name='ActuationRead'),

    url(r'^ActuatableProperty/(?P<pk>\d+)/read/$', Read_view.ActuatablePropertyRead, name='ActuatablePropertyRead'),

    url(r'^Observation/(?P<pk>\d+)/read/$', Read_view.ObservationRead, name='ObservationRead'),

    url(r'^Sampling/(?P<pk>\d+)/read/$', Read_view.SamplingRead, name='SamplingRead'),

    url(r'^FeatureOfInterest/(?P<pk>\d+)/read/$', Read_view.FeatureOfInterestRead, name='FeatureOfInterestRead'),

    url(r'^Sample/(?P<pk>\d+)/read/$', Read_view.SampleRead, name='SampleRead'),

    url(r'^Result/(?P<pk>\d+)/read/$', Read_view.ResultRead, name='ResultRead'),

    url(r'^Platform/(?P<pk>\d+)/read/$', Read_view.PlatformRead, name='PlatformRead'),

    url(r'^Actuator/(?P<pk>\d+)/read/$', Read_view.ActuatorRead, name='ActuatorRead'),

    url(r'^Sampler/(?P<pk>\d+)/read/$', Read_view.SamplerRead, name='SamplerRead'),

    url(r'^Sensor/(?P<pk>\d+)/read/$', Read_view.SensorRead, name='SensorRead'),

    url(r'^ObservableProperty/(?P<pk>\d+)/read/$', Read_view.ObservablePropertyRead, name='ObservablePropertyRead'),


    url(r'^Agent/list/$', List_view.AgentList, name='AgentList'),

    url(r'^TemporalEntity/list/$', List_view.TemporalEntityList, name='TemporalEntityList'),

    url(r'^Procedure/list/$', List_view.ProcedureList, name='ProcedureList'),

    url(r'^Vocabulary/list/$', List_view.VocabularyList, name='VocabularyList'),

    url(r'^Actuation/list/$', List_view.ActuationList, name='ActuationList'),

    url(r'^ActuatableProperty/list/$', List_view.ActuatablePropertyList, name='ActuatablePropertyList'),

    url(r'^Observation/list/$', List_view.ObservationList, name='ObservationList'),

    url(r'^Sampling/list/$', List_view.SamplingList, name='SamplingList'),

    url(r'^FeatureOfInterest/list/$', List_view.FeatureOfInterestList, name='FeatureOfInterestList'),

    url(r'^Sample/list/$', List_view.SampleList, name='SampleList'),

    url(r'^Result/list/$', List_view.ResultList, name='ResultList'),

    url(r'^Platform/list/$', List_view.PlatformList, name='PlatformList'),

    url(r'^Actuator/list/$', List_view.ActuatorList, name='ActuatorList'),

    url(r'^Sampler/list/$', List_view.SamplerList, name='SamplerList'),

    url(r'^Sensor/list/$', List_view.SensorList, name='SensorList'),

    url(r'^ObservableProperty/list/$', List_view.ObservablePropertyList, name='ObservablePropertyList'),


    url(r'^Agent/(?P<pk>\d+)/update/$', Update_view.AgentUpdate, name='AgentUpdate'),

    url(r'^TemporalEntity/(?P<pk>\d+)/update/$', Update_view.TemporalEntityUpdate, name='TemporalEntityUpdate'),

    url(r'^Procedure/(?P<pk>\d+)/update/$', Update_view.ProcedureUpdate, name='ProcedureUpdate'),

    url(r'^Vocabulary/(?P<pk>\d+)/update/$', Update_view.VocabularyUpdate, name='VocabularyUpdate'),

    url(r'^Actuation/(?P<pk>\d+)/update/$', Update_view.ActuationUpdate, name='ActuationUpdate'),

    url(r'^ActuatableProperty/(?P<pk>\d+)/update/$', Update_view.ActuatablePropertyUpdate, name='ActuatablePropertyUpdate'),

    url(r'^Observation/(?P<pk>\d+)/update/$', Update_view.ObservationUpdate, name='ObservationUpdate'),

    url(r'^Sampling/(?P<pk>\d+)/update/$', Update_view.SamplingUpdate, name='SamplingUpdate'),

    url(r'^FeatureOfInterest/(?P<pk>\d+)/update/$', Update_view.FeatureOfInterestUpdate, name='FeatureOfInterestUpdate'),

    url(r'^Sample/(?P<pk>\d+)/update/$', Update_view.SampleUpdate, name='SampleUpdate'),

    url(r'^Result/(?P<pk>\d+)/update/$', Update_view.ResultUpdate, name='ResultUpdate'),

    url(r'^Platform/(?P<pk>\d+)/update/$', Update_view.PlatformUpdate, name='PlatformUpdate'),

    url(r'^Actuator/(?P<pk>\d+)/update/$', Update_view.ActuatorUpdate, name='ActuatorUpdate'),

    url(r'^Sampler/(?P<pk>\d+)/update/$', Update_view.SamplerUpdate, name='SamplerUpdate'),

    url(r'^Sensor/(?P<pk>\d+)/update/$', Update_view.SensorUpdate, name='SensorUpdate'),

    url(r'^ObservableProperty/(?P<pk>\d+)/update/$', Update_view.ObservablePropertyUpdate, name='ObservablePropertyUpdate'),


    url(r'^Agent/(?P<pk>\d+)/delete/$', Delete_view.AgentDelete, name='AgentDelete'),

    url(r'^TemporalEntity/(?P<pk>\d+)/delete/$', Delete_view.TemporalEntityDelete, name='TemporalEntityDelete'),

    url(r'^Procedure/(?P<pk>\d+)/delete/$', Delete_view.ProcedureDelete, name='ProcedureDelete'),

    url(r'^Vocabulary/(?P<pk>\d+)/delete/$', Delete_view.VocabularyDelete, name='VocabularyDelete'),

    url(r'^Actuation/(?P<pk>\d+)/delete/$', Delete_view.ActuationDelete, name='ActuationDelete'),

    url(r'^ActuatableProperty/(?P<pk>\d+)/delete/$', Delete_view.ActuatablePropertyDelete, name='ActuatablePropertyDelete'),

    url(r'^Observation/(?P<pk>\d+)/delete/$', Delete_view.ObservationDelete, name='ObservationDelete'),

    url(r'^Sampling/(?P<pk>\d+)/delete/$', Delete_view.SamplingDelete, name='SamplingDelete'),

    url(r'^FeatureOfInterest/(?P<pk>\d+)/delete/$', Delete_view.FeatureOfInterestDelete, name='FeatureOfInterestDelete'),

    url(r'^Sample/(?P<pk>\d+)/delete/$', Delete_view.SampleDelete, name='SampleDelete'),

    url(r'^Result/(?P<pk>\d+)/delete/$', Delete_view.ResultDelete, name='ResultDelete'),

    url(r'^Platform/(?P<pk>\d+)/delete/$', Delete_view.PlatformDelete, name='PlatformDelete'),

    url(r'^Actuator/(?P<pk>\d+)/delete/$', Delete_view.ActuatorDelete, name='ActuatorDelete'),

    url(r'^Sampler/(?P<pk>\d+)/delete/$', Delete_view.SamplerDelete, name='SamplerDelete'),

    url(r'^Sensor/(?P<pk>\d+)/delete/$', Delete_view.SensorDelete, name='SensorDelete'),

    url(r'^ObservableProperty/(?P<pk>\d+)/delete/$', Delete_view.ObservablePropertyDelete, name='ObservablePropertyDelete'),

    ]

sosa_project/sosa_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'sosa_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^vowl', 'sosa_app.Home_view.vowl', name='vowl'),
    url(r'^sosa_app/', include('sosa_app.urls', namespace='sosa_app')),
    url(r'^$', 'sosa_app.Home_view.HomeView', name='HomeView'),    url(r'^accounts/',include('django.contrib.auth.urls')),]

sosa_project/sosa_app/models.py
from django.db import models

class Agent(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class TemporalEntity(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Procedure(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Vocabulary(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Actuation(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class ActuatableProperty(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Observation(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Sampling(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class FeatureOfInterest(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Sample(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Result(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Platform(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Actuator(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Sampler(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class Sensor(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

class ObservableProperty(models.Model):
    
    name=models.CharField(max_length = 50)
    
    def __str__(self):
        return self.name

sosa_project/sosa_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class AgentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AgentForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Agent
        exclude = ()

class TemporalEntityForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TemporalEntityForm, self).__init__(*args, **kwargs)
    class Meta:
        model = TemporalEntity
        exclude = ()

class ProcedureForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProcedureForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Procedure
        exclude = ()

class VocabularyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(VocabularyForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Vocabulary
        exclude = ()

class ActuationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ActuationForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Actuation
        exclude = ()

class ActuatablePropertyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ActuatablePropertyForm, self).__init__(*args, **kwargs)
    class Meta:
        model = ActuatableProperty
        exclude = ()

class ObservationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ObservationForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Observation
        exclude = ()

class SamplingForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SamplingForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Sampling
        exclude = ()

class FeatureOfInterestForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(FeatureOfInterestForm, self).__init__(*args, **kwargs)
    class Meta:
        model = FeatureOfInterest
        exclude = ()

class SampleForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SampleForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Sample
        exclude = ()

class ResultForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ResultForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Result
        exclude = ()

class PlatformForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PlatformForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Platform
        exclude = ()

class ActuatorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ActuatorForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Actuator
        exclude = ()

class SamplerForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SamplerForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Sampler
        exclude = ()

class SensorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SensorForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Sensor
        exclude = ()

class ObservablePropertyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ObservablePropertyForm, self).__init__(*args, **kwargs)
    class Meta:
        model = ObservableProperty
        exclude = ()

sosa_project/sosa_app/views.py
from django.shortcuts import render

# Create your views here.

sosa_project/sosa_app/templates/ActuatablePropertyUpdate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'sosa_app:ActuatablePropertyUpdate' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Update</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

sosa_project/sosa_app/templates/AgentUpdate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'sosa_app:AgentUpdate' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Update</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

sosa_project/sosa_app/templates/ObservablePropertyUpdate.html
{% extends 'home.html'%}
{% block content %}
      <!-- Your Semantic UI Code -->  
      <div class="ui one column stackable center aligned page grid">
        <div class='column twelve wide'>
          <div class='ui center aligned segment container'>
              <form method = "post"  action = "{% url 'sosa_app:ObservablePropertyUpdate' form.instance.pk%}" class='ui form'>
              {% csrf_token %}
                    {% for field in form %}
                                    <div class='field form-group {% if field.errors %} has-error{% endif %}'>
                                        <label for='{{ field.id_for_label }}'>
                                            {{ field.label }}
                                        </label>
                                        {% for key, value in field_types.items %}
                                            {% if field.label == key%}
                                                 {% if value == 'SelectMultiple' %}
                                                    {% if  field.field.choices %}
                                                        {{ field }}
                                                    {%endif%}
                                                    {% for key, value in foreign_keys.items %}
                                                            {% if key == field.label %}
                                                                <a href="{% url value %}" class="item">Add</a>
                                                            {%endif%}
                                                    {% endfor %} 
                                                {% elif value == 'Select' %}
                                                            {% if field.field.choices|length > 1 %}
                                                                {{ field }}
                                                            {% endif %} 
                                                        <a>Add</a>
                                                {%else%}
                                                    {{ field }}
                                                {%endif%}
                                             {%endif%}
                                         {% endfor %}        
                                        {% for error in field.errors %}
                                            <p class="ui pointing  basic label">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                    {% endfor %}
                <div class="two ui buttons actions">
                            <button  type="button"  class="ui deny small button">Cancel</button>
                            <button  type="submit" class="ui positive small button submit">Update</button>
                </div>
              </form>
          </div>
        </div>
      </div> 
{% endblock %}

sosa_project/sosa_app/templates/ObservationList.html
{% extends 'home.html'%}
{% block content %}
        <div class='ui center aligned segment container'>
        <h2>Observation</h2>
        <div class="ui one column stackable center aligned page grid">
            <div class="twelve wide column">
                <a  href="{% url 'sosa_app:ObservationCreate'%}">
                        <button type="button">Create</button> 
                </a>
            </div>
            <div class='column twelve wide'>
            {% if  data %}
            <table class="ui celled table">
                <thead>
                    <tr>
                        {% for field in fields%}
                        <th>{{field}}</th>
                         {% endfor %}
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                     {% for instance in data %}
                        <tr>
                             {% for field, value in instance.fields.items %}
                            <td>
                             {{ value }}
                            </td>
                             {% endfor %}
                              <td>
                                <a href="{% url 'sosa_app:ObservationRead' instance.pk%}">
                                        <button>View</button>
                                </a>
                                 <a href="{% url 'sosa_app:ObservationUpdate' instance.pk %}">
                                        <button>Update</button>
                                 </a>
                                 <a href="{% url 'sosa_app:ObservationDelete' instance.pk %}">
                                        <button>Delete</button>
                                 </a>
                             </td>
                        <tr>
                         {% endfor %}
                    </tr>
                    </tbody>
            </table>
            {%endif%}
            </div>
        </div>
    </div>
{% endblock %}

sosa_project/sosa_app/templates/ObservationRead.html
{% extends 'home.html'%}
{% block content %}
<div class='ui center aligned segment container'>
    <div class="ui grid">
        <div class="ui column">
            <div class="ui segment">
                    {% for item in instance_items %}
                    <div class="item">
                        <div class="ui horizontal label">
                                    {{item.key}}
                                </div><span> {{item.value}}</span>
                    </div>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

sosa_project/sosa_app/templates/PlatformRead.html
{% extends 'home.html'%}
{% block content %}
<div class='ui center aligned segment container'>
    <div class="ui grid">
        <div class="ui column">
            <div class="ui segment">
                    {% for item in instance_items %}
                    <div class="item">
                        <div class="ui horizontal label">
                                    {{item.key}}
                                </div><span> {{item.value}}</span>
                    </div>
                    {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

sosa_project/sosa_app/templates/ResultList.html
{% extends 'home.html'%}
{% block content %}
        <div class='ui center aligned segment container'>
        <h2>Result</h2>
        <div class="ui one column stackable center aligned page grid">
            <div class="twelve wide column">
                <a  href="{% url 'sosa_app:ResultCreate'%}">
                        <button type="button">Create</button> 
                </a>
            </div>
            <div class='column twelve wide'>
            {% if  data %}
            <table class="ui celled table">
                <thead>
                    <tr>
                        {% for field in fields%}
                        <th>{{field}}</th>
                         {% endfor %}
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                     {% for instance in data %}
                        <tr>
                             {% for field, value in instance.fields.items %}
                            <td>
                             {{ value }}
                            </td>
                             {% endfor %}
                              <td>
                                <a href="{% url 'sosa_app:ResultRead' instance.pk%}">
                                        <button>View</button>
                                </a>
                                 <a href="{% url 'sosa_app:ResultUpdate' instance.pk %}">
                                        <button>Update</button>
                                 </a>
                                 <a href="{% url 'sosa_app:ResultDelete' instance.pk %}">
                                        <button>Delete</button>
                                 </a>
                             </td>
                        <tr>
                         {% endfor %}
                    </tr>
                    </tbody>
            </table>
            {%endif%}
            </div>
        </div>
    </div>
{% endblock %}

sosa_project/sosa_app/templates/SamplingList.html
{% extends 'home.html'%}
{% block content %}
        <div class='ui center aligned segment container'>
        <h2>Sampling</h2>
        <div class="ui one column stackable center aligned page grid">
            <div class="twelve wide column">
                <a  href="{% url 'sosa_app:SamplingCreate'%}">
                        <button type="button">Create</button> 
                </a>
            </div>
            <div class='column twelve wide'>
            {% if  data %}
            <table class="ui celled table">
                <thead>
                    <tr>
                        {% for field in fields%}
                        <th>{{field}}</th>
                         {% endfor %}
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                     {% for instance in data %}
                        <tr>
                             {% for field, value in instance.fields.items %}
                            <td>
                             {{ value }}
                            </td>
                             {% endfor %}
                              <td>
                                <a href="{% url 'sosa_app:SamplingRead' instance.pk%}">
                                        <button>View</button>
                                </a>
                                 <a href="{% url 'sosa_app:SamplingUpdate' instance.pk %}">
                                        <button>Update</button>
                                 </a>
                                 <a href="{% url 'sosa_app:SamplingDelete' instance.pk %}">
                                        <button>Delete</button>
                                 </a>
                             </td>
                        <tr>
                         {% endfor %}
                    </tr>
                    </tbody>
            </table>
            {%endif%}
            </div>
        </div>
    </div>
{% endblock %}